name: Deploy to Render with Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Flask Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and deploy to Render
      run: |
        render deploy --github-auto-preview --name customers-orders-service --branch main --build-command "pip install -r requirements.txt" --start-command "flask run"




