name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest

deploy:
  needs: build
  runs-on: ubuntu-latest
  if: github.ref == 'refs/heads/main' && github.event_name == 'push'

  steps:
    - name: Install Render CLI
      run: |
        curl -sL https://render.com/install.sh | bash

    - name: Authenticate with Render
      run: render auth

    - name: Build Application
      run: |
         flask run

    - name: Deploy to Render
      run: render deploy -- --auto

    - name: Monitor Deployment
      run: render logs



