name: Deploy to Render with Testing

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Flask Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python -m unittest discover -s tests

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Render CLI
      uses: renderapp/action-setup-render-cli@v1
      with:
        render-token: ${{ secrets.rnd_a8a8wECZyQc4sqZvK0rday2b5MKA }}

    - name: Configure Render
      run: |
        render configure --account-id ${{ secrets.vera }} --token ${{ secrets.rnd_a8a8wECZyQc4sqZvK0rday2b5MKA }}

    - name: Build and deploy to Render
      run: |
        render deploy --github-auto-preview --name my-flask-app --branch main --build-command "pip install -r requirements.txt" --start-command "python3 app.py"




